class Config:
    font_path = ''
    pixels_per_sec = int(450 * 0.8)
    track_width = int(600 * 0.8)
    page_target_height = int(4800 * 0.8)
    page_time_column_width = 112
    page_gap = 32
    page_padding = 24
    page_time_font_size = 32
    page_time_label_gap = 12
    page_time_color = 0xFFB9C4D2
    page_combo_font_size = 26
    page_combo_gap = 6
    page_combo_color = 0xFF8E9AAA
    page_rhythm_column_width = 80
    page_rhythm_font_size = 32
    page_rhythm_label_gap = 12
    page_rhythm_color = 0xFFB9C4D2
    page_background_color = 0xFF0B1018
    footer_height = 360
    tap_image_path = './tap.png'
    hold_image_path = './hold.png'
    tap_left_color = 0xFF8B66F0
    tap_right_color = 0xFFE05C88
    hold_color = 0xFF3C92C7
    tap_color = hold_color
    directional_flick_right_color = 0xB05AE0A1
    directional_flick_left_color = 0xB0F6D84A
    directional_flick_height = 64
    directional_flick_tip_inset = 45
    directional_flick_tail_scale = 80
    directional_flick_glow_blur = 4
    directional_flick_edge_width = 2
    # ARGB: the low alpha keeps lane colors and notes visible through the field.
    skyarea_fill_color = 0x50927AE7
    skyarea_edge_glow_color = 0x668A70FF
    skyarea_edge_color = 0xFFF1EAFF
    skyarea_edge_glow_width = 5
    skyarea_edge_glow_blur = 3
    skyarea_edge_width = 2
